# Googling how to do something is NOT cheating. 
# Googling how to do figure something out is ENCOURAGED.

## #1 Figure out how to print the current date and time. 
The solution should be in this format:  2021-08-05 11:56:30 (YYYY-MM-DD HH:MM:SS)

Hint:  You're going to have to import a library

In [4]:
from datetime import datetime

now = datetime.now()

print(now)

2026-08-05 16:39:26.034074

## #2 Write a function that accepts the radius of a circle and returns the area of a circle.  
The function for the area of a circle is pi * radius squared.

In [8]:
import math as m

def area(r):
    return m.pi * (r ** 2)

radius = int(input("Enter a radius"))
area(radius)

ValueError: invalid literal for int() with base 10: ''

## #3 Write a function that takes a list of numbers and returns True of all number in the list are unique and returns False if the list contains duplicate numbers. 
* Hint, maybe think of using a set()

Input:  input_list = [2,4,5,5,7,9]

Expected Output:  False

In [25]:
def unique(x):
    b = list(set(x))
    x.sort()
    if b == x:
        return True
    else:
        return False

x = [2,4,5,3,6,67,5,7,9]

unique(x)

False

## #4 Write a Python program to count the number of each character of a given text of a text file.
* Use the text file called 'lil-wayne.txt' in the data folder.  
* Convert all the characters to uppercase first, then count them.  
* Use a dictionary in which the keys of the dictionary are the characters, and the values are the counts of that character. 

Expected Result:  `{'D': 74, 'W': 63, 'A': 211, 'Y': 44, 'N': 165, 'E': 274, ' ': 522, 'M': 77, 'I': 185, 'C': 60, 'H': 122, 'L': 126, 'R': 152, 'T': 180, 'J': 8, '.': 26, '(': 12, 'B': 59, 'O': 145, 'S': 152, 'P': 39, '2': 24, '7': 7, ',': 37, '1': 28, '9': 16, '8': 6, ')': 12, '[': 14, ']': 14, 'K': 13, 'F': 44, 'G': 53, 'X': 5, 'U': 66, 'V': 20, '3': 2, '4': 4, '5': 5, '6': 3, '0': 36, '\n': 6, '-': 6, ';': 1, '!': 1, '"': 8, "'": 3, '—': 1}`

In [52]:
with open("../Week-02/intermediate/data/lil-wayne.txt", "r") as file:    #open file with read permission and set it as file
    content = file.read()                 #stores the file into content

with open("../Week-02/intermediate/data/lil-wayne.txt", "w") as file:           #open file with write permission
    file.write(content.upper())                  #overwrites file with .upper()  <-- overwrites all into uppercase into that file

dictionary = {}

with open("../Week-02/intermediate/data/lil-wayne.txt", "r") as file:
    for word in file:                 #each word in file
        for letter in word:                        #each letter in word
            if letter not in dictionary:            # if letter not in dictionary, #append it as a (letter): 1
                dictionary[letter] = 1             
            else:                                       #or else, append the existing letter by 1 
                dictionary[letter] += 1                 

print(dictionary)           #printing dictionary

{'D': 74, 'W': 63, 'A': 211, 'Y': 44, 'N': 165, 'E': 274, ' ': 522, 'M': 77, 'I': 185, 'C': 60, 'H': 122, 'L': 126, 'R': 152, 'T': 180, 'J': 8, '.': 26, '(': 12, 'B': 59, 'O': 145, 'S': 152, 'P': 39, '2': 24, '7': 7, ',': 37, '1': 28, '9': 16, '8': 6, ')': 12, '[': 14, ']': 14, 'K': 13, 'F': 44, 'G': 53, 'X': 5, 'U': 66, 'V': 20, '3': 2, '4': 4, '5': 5, '6': 3, '0': 36, '\n': 6, '-': 6, ';': 1, '!': 1, 'Â': 1, '€': 1, '”': 1}

# 4.5 Figure out how to sort the dictionary to find which character appears the most.

In [ ]:
import numpy as np

k = list(dictionary.keys())                    #set keys and values as seperate list
d = list(dictionary.values())

idx = reversed(np.argsort(d))            #sort the array from least to most (the array that forms it is the index of it) and reverses the index

res = {k[i]: d[i] for i in idx}          #for loop and forms a new dictionary as you trace through the reversed index

print(res)

{' ': 522, 'E': 274, 'A': 211, 'I': 185, 'T': 180, 'N': 165, 'R': 152, 'S': 152, 'O': 145, 'L': 126, 'H': 122, 'M': 77, 'D': 74, 'U': 66, 'W': 63, 'C': 60, 'B': 59, 'G': 53, 'F': 44, 'Y': 44, 'P': 39, ',': 37, '0': 36, '1': 28, '.': 26, '2': 24, 'V': 20, '9': 16, ']': 14, '[': 14, 'K': 13, '(': 12, ')': 12, 'J': 8, '7': 7, '\n': 6, '-': 6, '8': 6, 'X': 5, '5': 5, '4': 4, '6': 3, '3': 2, '!': 1, ';': 1, 'Â': 1, '€': 1, '”': 1}

## #5 Using the list below...
* Remove the fourth number from the list.
* Take that number you just removed and multiply the last number of the list by that number. 
* Append that number to the end of the list.
* Print the list

INPUT: [1, 1, 2, 3, 5, 8, 13, 21]

EXPECTED OUTPUT:  [1, 1, 2, 5, 8, 13, 21, 63]

In [58]:
list1 = [1, 1, 2, 3, 5, 8, 13, 21]

x = list1[3]
list1.pop(3)

result = x * list1[-1]

list1.append(result)
print(list1)

[1, 1, 2, 5, 8, 13, 21, 63]

## #6 Using the list below, make a new list that contains only the numbers from the original list that are divisible by three.

* Input:  original_list = [2, 3, 6, 8, 9, 15, 19, 21]
* Expected new list:  [3, 6, 9, 15, 21]

In [59]:
original_list = [2, 3, 6, 8, 9, 15, 19, 21]
new_list = []

for i in original_list:
    if i % 3 == 0:
        new_list.append(i)
print(new_list)

[3, 6, 9, 15, 21]

## #7 Reverse the list below

In [60]:
original_list = [2, 3, 6, 8, 9, 15, 19, 21]

original_list.reverse()

print(original_list)

[21, 19, 15, 9, 8, 6, 3, 2]

## #8 Using the list below, turn every item of the list into its square.  
* Input original_list = [1, 2, 3, 4, 5, 6, 7]
* Expected new_list:  [1, 4, 9, 16, 25, 36, 49]

In [62]:
original_list = [1, 2, 3, 4, 5, 6, 7]

squared_list = [i ** 2 for i in original_list]

print(squared_list)

[1, 4, 9, 16, 25, 36, 49]

## #9  Given a two Python list. Iterate both lists simultaneously such that list1 should display item in original order and list2 in reverse order.
Given input:
```
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
```

Expected Output:
```
10 400
20 300
30 200
40 100
```

In [ ]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]

list2.reverse()

count = 0
n = len(list1) - 1


while count <= n:
    print(f'{list1[count]} {list2[count]}')
    count += 1

10 400
20 300
30 200
40 100

## #10 Remove empty strings from the list of strings.
Input:  `list_of_strings = ['I', 'love', '', '', 'data', '', 'science', '!']`

Expected Output:  `['I', 'love', 'data', 'science', '!']`

In [ ]:
list_of_strings = ['I', 'love', '', '', 'data', '', 'science', '!']

'''
for i in list_of_strings:
    if i.strip():
        z.append(i)
print(z)
'''

list_of_strings = [i for i in list_of_strings if i.strip()]
print(list_of_strings)

['I', 'love', 'data', 'science', '!']

##  #11 Check if the value 999 exists in the dicitionary below.  If so, print true, if not print false.

Input: sample_dict = {'a': 100, 'b': 999, 'c': 300}

Expected Output:  True

In [ ]:
sample_dict = {'a': 100, 'b': 999, 'c': 300}

values = sample_dict.values()

if 999 in values:
    print(True)
else:
    print(False)

False

# #12 Fix all the follow broken code snippets below
(I got these examples from a great website, I will reference them later because they have the answers on them.)

In [95]:
greeting = "Hello, possible pirate! What's the password?"
password = 'admin'
message = greeting+password
if message in ["Arrr!"]:
	print("Go away, pirate.")
else:
 print("Greetings, hater of pirates!")

Greetings, hater of pirates!

In [98]:
pages = 457
word_per_page = 250
number_of_pieces = 100

each_chunk = (457 * 250) /10
print(each_chunk)

11425.0

# Extra Credit

## Using pandas, read the csv file in the data folder called `titianic.csv` and store it as a variable named `df`.

In [102]:
import pandas as pd

df = pd.read_csv("../Week-02/intermediate/data/titanic.csv")

df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## I know we didn't cover this, but figure out how to find the mean age of the age column in your dataframe.

In [105]:
average = df["age"].mean()
print(average)

29.69911764705882

## What was the oldest and youngest ages on the titanic?

In [ ]:
highest = df["age"].max()
lowest = df["age"].min()

print(f'highest age is {highest}')
print(f'lowest age is {lowest}')

highest age is 80.0
lowest age is 0.42

,passengerid,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## How many people embarked from station 'S'?

In [119]:
station_s = len(df[df["embarked"] == "S"])

'''
df["embarked"] == "S" sets each row of the embarked column as:
        True, if that row's column of embarked is S
        False, if that row's column of embarked is not S

        then the outside df[] only shows the column where embarked is True

        len() then counts the total number of rows that embarked has
'''
print(len(df["embarked"]))
print(len(df[df["embarked"] == "S"]))

print(f'{station_s} number of people embarked from station S')

891
644
644 number of people embarked from station S